# Generated by Django 2.2.5 on 2022-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code3',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
