# Generated by Django 2.2.5 on 2022-03-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0002_auto_20220324_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('logo', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=16, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Country')),
            ],
            options={
                'ordering': ['countryid', 'name'],
            },
        ),
    ]
