# Generated by Django 2.2.5 on 2022-03-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0003_auto_20220326_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['country', 'name']},
        ),
        migrations.RenameField(
            model_name='league',
            old_name='countryid',
            new_name='country',
        ),
    ]
