# Generated by Django 2.2.5 on 2022-03-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0004_auto_20220326_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('current', models.BooleanField()),
                ('logo', models.CharField(max_length=256, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('last_updated', models.DateField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.League')),
            ],
            options={
                'ordering': ['league', '-year'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('year', 'league'), name='unique_season'),
        ),
    ]
