# Generated by Django 2.2.5 on 2022-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0005_auto_20220326_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
