# Generated by Django 2.2.5 on 2022-03-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0006_auto_20220327_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('logo', models.CharField(max_length=256, null=True)),
                ('national', models.BooleanField()),
                ('code', models.CharField(max_length=16, null=True)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.CreateModel(
            name='TeamToSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Team')),
            ],
            options={
                'ordering': ['team', '-season'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Country'),
        ),
        migrations.AddConstraint(
            model_name='teamtoseason',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_team_to_season'),
        ),
    ]
