# Generated by Django 2.2.5 on 2022-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0008_team_alt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='alt_name',
        ),
        migrations.AddField(
            model_name='country',
            name='alt_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
