# Generated by Django 2.2.5 on 2022-03-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0009_auto_20220327_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status_long', models.CharField(max_length=32)),
                ('status_short', models.CharField(max_length=16)),
                ('round', models.CharField(max_length=64)),
                ('homescore_ht', models.IntegerField(null=True)),
                ('awayscore_ht', models.IntegerField(null=True)),
                ('homescore_ft', models.IntegerField(null=True)),
                ('awayscore_ft', models.IntegerField(null=True)),
                ('homescore_et', models.IntegerField(null=True)),
                ('awayscore_et', models.IntegerField(null=True)),
                ('homescore_p', models.IntegerField(null=True)),
                ('awayscore_p', models.IntegerField(null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='sportwettenratings.TeamToSeason')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='sportwettenratings.TeamToSeason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Season')),
            ],
            options={
                'ordering': ['season', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sidelined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportwettenratings.Fixture')),
                ('shots_on_goal_h', models.IntegerField(null=True)),
                ('shots_on_goal_a', models.IntegerField(null=True)),
                ('shots_off_goal_h', models.IntegerField(null=True)),
                ('shots_off_goal_a', models.IntegerField(null=True)),
                ('total_shots_h', models.IntegerField(null=True)),
                ('total_shots_a', models.IntegerField(null=True)),
                ('blocked_shots_h', models.IntegerField(null=True)),
                ('blocked_shots_a', models.IntegerField(null=True)),
                ('shots_insidebox_h', models.IntegerField(null=True)),
                ('shots_insidebox_a', models.IntegerField(null=True)),
                ('shots_outsidebox_h', models.IntegerField(null=True)),
                ('shots_outsidebox_a', models.IntegerField(null=True)),
                ('fouls_h', models.IntegerField(null=True)),
                ('fouls_a', models.IntegerField(null=True)),
                ('corner_kicks_h', models.IntegerField(null=True)),
                ('corner_kicks_a', models.IntegerField(null=True)),
                ('offsides_h', models.IntegerField(null=True)),
                ('offsides_a', models.IntegerField(null=True)),
                ('ball_possession_h', models.FloatField(null=True)),
                ('ball_possession_a', models.FloatField(null=True)),
                ('yellow_cards_h', models.IntegerField(null=True)),
                ('yellow_cards_a', models.IntegerField(null=True)),
                ('red_cards_h', models.IntegerField(null=True)),
                ('red_cards_a', models.IntegerField(null=True)),
                ('goalkeeper_saves_h', models.IntegerField(null=True)),
                ('goalkeeper_saves_a', models.IntegerField(null=True)),
                ('total_passes_h', models.IntegerField(null=True)),
                ('total_passes_a', models.IntegerField(null=True)),
                ('passes_accurate_h', models.IntegerField(null=True)),
                ('passes_accurate_a', models.IntegerField(null=True)),
                ('passes_percent_h', models.FloatField(null=True)),
                ('passes_percent_a', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('odd', models.FloatField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Bet')),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Bookmaker')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Fixture')),
            ],
            options={
                'ordering': ['match', 'bet', 'bookmaker'],
            },
        ),
        migrations.AddConstraint(
            model_name='odd',
            constraint=models.UniqueConstraint(fields=('match', 'bookmaker', 'bet', 'value'), name='unique_odd'),
        ),
    ]
