# Generated by Django 2.2.5 on 2022-03-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0010_auto_20220328_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Sidelined',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='Trophy',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
