# Generated by Django 2.2.5 on 2022-03-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0013_auto_20220331_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportwettenratings.Fixture'),
        ),
    ]
