# Generated by Django 2.2.5 on 2022-04-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0014_auto_20220331_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=64)),
                ('birth_country', models.CharField(max_length=64)),
                ('nationality', models.CharField(max_length=64)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('injured', models.BooleanField()),
                ('photo', models.CharField(max_length=256, null=True)),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.TeamToSeason')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.IntegerField()),
                ('time_extra', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=64, null=True)),
                ('assist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='sportwettenratings.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='sportwettenratings.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportwettenratings.TeamToSeason')),
            ],
        ),
    ]
