# Generated by Django 2.2.5 on 2022-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0015_event_player_playerteamseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_place',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
