# Generated by Django 2.2.5 on 2022-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0017_auto_20220405_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='goal_attempts_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='goal_attempts_h',
            field=models.IntegerField(null=True),
        ),
    ]
