# Generated by Django 2.2.5 on 2022-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportwettenratings', '0018_auto_20220405_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='goals_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='goals_h',
            field=models.IntegerField(null=True),
        ),
    ]
